// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urznhyxtzhgplepznojd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVyem5oeXh0emhncGxlcHpub2pkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0NjQ0MzMsImV4cCI6MjA2ODA0MDQzM30.k7aj9U7-V4gGXKIwD2-SNqC7YeitMispg1TBSElVz2c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});