// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://unltifpjzgluddxugnup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVubHRpZnBqemdsdWRkeHVnbnVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MTYwNDcsImV4cCI6MjA2MzI5MjA0N30.IW1FKg6i0yX0NXhIW7JdKNF88AfxlDch9GMl4LNsaZ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);